_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.3
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
exclude:
    value: mrsa
l1_strength:
    value: 250
threshold:
    value: 5
