[tool.poetry]
name = "mrsa_ca_rna"
version = "0.1.0"
description = ""
authors = ["MrBones1102 <jamespopoli@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.5.0"
matplotlib = "^3.9.0"
ipympl = "^0.9.4"
pandas = "^2.2.2"
seaborn = "^0.13.2"
svgutils = "^0.3.4"
ruff = "^0.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
